### ISSUE TITLE
Not working in device

### ISSUE THREAD

**Issue by dungtv1991** [krzysztofzablocki/Inject#45]
Please update for device

**Comment by johnno1962** [comment]
HI, What is not working on a device? It doesn't compile,  inject, /update? On-device injection isn't really supported as it is technically difficult and has many limitations.

**Comment by icedice** [comment]
I was wondering about this as well. I realise that injection on the device is very experimental but it is also extremely cool and useful so I really want to get it working.  For me what is happening is that it never connects, in fact nothing is outputtet to the console at all.  

I did mange to get device injection to work using the [HotReloading](https://github.com/johnno1962/HotReloading) project, but I prefer this way for ease of use and because I'm having issues with hot refreshing collectionView cells with the HotReloading project which seems to work out of the box using this. It was my understanding that this project and the HotReloading project connects to the [InjectionIII](https://github.com/johnno1962/InjectionIII) app the same way which is way I'm confused why device reloading works with HotReloading but not with Inject....
