### ISSUE TITLE
Only add on root view (SwiftUI)

### ISSUE THREAD

**Issue by Tulleb** [krzysztofzablocki/Inject#76]
Would it be possible to only add the prerequisites (`.enableInjection()` & `@ObserveInjection var inject`) on our root view so it is automatically working for all subviews hierarchy?

Here it is working but I have to reinitiate the view (dismiss / reinit) it for my changes to display.

Amazing lib btw 👏👏👏

**Comment by johnno1962** [comment]
Hi, I wish it were possible but it's not due to technical details of how SwiftUI and opaque (some View) types work. 

You need to erase the type at every level you want to be able to inject using `.enableInjection()` or it is possible there is a disagreement on the memory layout of the concrete return type of a body property between injected an un-injected code. 

Adding an observer at each level is necessary as SwiftU caches a representation of the current UI at each level. Without the observer you can't guarantee a View will redraw when you inject it even if its superview is marked as having changed. 

If you are using the app, there is an option "Prepare Project" on the menu bar that goes through all sources of your app and tries to make these changes automatically though YMMV.

**Comment by johnno1962** [comment]
Yes, the InjectionIII.app. When you run it there should be a little blue syringe on the menu bar at the top right of your screen. Open your project using the menu item that pops down, then select "Prepare Project".
